---
name: test
on:
  workflow_call:
    inputs:
      aqua_version:
        required: true
        type: string
      go-version-file:
        required: false
        default: go.mod
        type: string
      golangci-lint-timeout:
        required: false
        type: string
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: false
permissions: {}
jobs:
  go:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@f0dafddd9f9075a33e4ff40a44bdabd79335e7a3 # v3.1.1
    with:
      aqua_version: ${{inputs.aqua_version}}
      go-version-file: ${{inputs.go-version-file}}
      golangci-lint-timeout: ${{inputs.golangci-lint-timeout}}
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      pull-requests: write
      contents: read
      id-token: write

  test:
    uses: suzuki-shunsuke/test-workflow/.github/workflows/test.yaml@51ece8dcaabff59820bfb2053c56e3cb281cf7b2 # v0.0.1
    with:
      aqua_version: ${{inputs.aqua_version}}
    permissions:
      pull-requests: read
      contents: read
